name: CI

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_LOGIN }}/posh-client

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log into Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin

      - name: Build image
        run: |
          docker build \
            -t ${DOCKER_IMAGE_NAME}:latest \
            .

      - name: Push images
        run: |
          docker push --all-tags ${DOCKER_IMAGE_NAME}

  deploy_contabo:
    needs: build-push

    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            manage-docker pull-restart posh-client prod
